### ISSUE TITLE
在popup组件里使用scroll-view组件导致scroll-view滚动不了

### ISSUE THREAD

**Issue by JanlyH** [Alibaba-mp/mini-ali-ui#10]
在popup组件里使用scroll-view组件导致scroll-view滚动不了，在编辑器是可以正常滚动，到真机调试或者发布都滚动不了

**Comment by linxz** [comment]
添加 `disableScroll` 为 **false** 应该就可以解决你的问题了。

**Comment by FrameJ** [comment]
是不是可以将pop-up组件的disable-scroll绑定的位置移动到mask上，一般用于屏蔽背景的滚动，而不影响弹窗内部的滚动
