### ISSUE TITLE
button组件使用data-xxx携带的参数无法在事件中获取

### ISSUE THREAD

**Issue by viis233** [Alibaba-mp/mini-ali-ui#13]
button组件使用data-xxx携带的参数无法在事件中获取
![TIM图片20200325195956](https://user-images.githubusercontent.com/41282272/77534224-3a179400-6ed3-11ea-87d8-e3c9ab065358.png)
![TIM截图20200325200021](https://user-images.githubusercontent.com/41282272/77534293-53204500-6ed3-11ea-8638-688c9bde4d84.png)

**Comment by linxz** [comment]
已在 1.0.10 版本中修复
