### ISSUE TITLE
横向tabs组件, 激活项无法回滚到中心位置

### ISSUE THREAD

**Issue by lumeme** [Alibaba-mp/mini-ali-ui#14]
应用: 钉钉小程序企业内部开发
mini-ali-ui版本: 1.0.5 or 1.0.6    

问题: 组件tabs切换,   激活项不会回滚到中间?

期望效果: 支付宝小程序官网的示例可以回滚https://opendocs.alipay.com/mini/component-ext/tabs

**Comment by linxz** [comment]
@lumeme 钉钉小程序的 SDK 可以升级了，可参考 https://ding-doc.dingtalk.com/doc#/dev/hi3eyb/RywtO

升级这个钉钉的 V2 引擎后就可以了正常使用了。
