### ISSUE TITLE
1.0.7之后外部改变checked绑定值，am-checkbox不再响应变化

### ISSUE THREAD

**Issue by FrameJ** [Alibaba-mp/mini-ali-ui#17]
1.0.7之后外部改变checked绑定值，am-checkbox不再响应变化

`<view>
  <am-checkbox checked="{{checked1}}" onChange="checkChange" data-index="1"></am-checkbox>
  <am-checkbox checked="{{checked2}}" onChange="checkChange" data-index="2"></am-checkbox>
  <am-checkbox checked="{{checked3}}" onChange="checkChange" data-index="3"></am-checkbox>
  <button size="default" type="primary" onTap="checkAll">CheckAll</button>
</view>`

`Page({
  data: {
    checked1: false,
    checked2: false,
    checked3: false,
  },
  checkChange(e) {
    console.log(e)
    this.setData({
      ['checked' + e.currentTarget.dataset.index]: e.detail.value,
    })
  },
  checkAll(e) {
    console.log(e)
    this.setData({
      checked1: true,
      checked2: true,
      checked3: true,
    })
  },
});`

_Originally posted by @FrameJ in https://github.com/Alibaba-mp/mini-ali-ui/pull/16#issuecomment-614502601_

**Comment by linxz** [comment]
1.0.9 版本中已加入可控操作
