### ISSUE TITLE
Tab + Popover一同使用导致Mask定位错误

### ISSUE THREAD

**Issue by nekronhuang** [Alibaba-mp/mini-ali-ui#20]
当Tab内部使用Popover时，由于`am-tabs-slides`的样式里存在`transform`，会导致mask的fixed定位出问题。[MDN position](https://developer.mozilla.org/zh-CN/docs/Web/CSS/position)

<img width="200" src="https://user-images.githubusercontent.com/6133789/81269710-4e2ae580-907c-11ea-9ff5-c8710371e66f.jpg" />

关闭swipeable，也是同样现象，估计使用的swiper也是相同原因。

PS：
刚接触小程序。。。不知道是否有类似React Portal的实现方式？

**Comment by linxz** [comment]
在 [1.0.11](https://github.com/Alibaba-mp/mini-ali-ui/releases/tag/1.0.11) 版本中可通过添加 `fixMaskFull` 属性来处理。参考文档说明：https://github.com/Alibaba-mp/mini-ali-ui/blob/master/src/popover/index.md
