### ISSUE TITLE
list-item组件能不能直接带url属性作为navigator跳转

### ISSUE THREAD

**Issue by footerbird** [Alibaba-mp/mini-ali-ui#21]
Do you want to request a feature or report a bug?

What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code.

What is the expected behavior?

Which versions of ``mini-ali-ui``, and which version of ``Alipay`` are affected by this issue? Did this work in previous versions of ``mini-ali-ui``?

**Comment by linxz** [comment]
可将 mini-ali-ui 更新到 [1.0.11](https://github.com/Alibaba-mp/mini-ali-ui/releases/tag/1.0.11) 版本，然后在 **list-item** 中通过 `data-url="pages/index/index"` 作为传参方式来处理。

![image](https://user-images.githubusercontent.com/1132815/83717040-31c29e80-a664-11ea-8004-08f3e1565948.png)

![image](https://user-images.githubusercontent.com/1132815/83717025-2a02fa00-a664-11ea-837f-19c463de0866.png)
