### ISSUE TITLE
mini-ali-ui-rpx Am-switch 开关 样式在不同机型上有问题

### ISSUE THREAD

**Issue by OneAndOnly1111** [Alibaba-mp/mini-ali-ui#23]
Do you want to request a feature or report a bug?

What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code.

What is the expected behavior?

Which versions of ``mini-ali-ui``, and which version of ``Alipay`` are affected by this issue? Did this work in previous versions of ``mini-ali-ui``?

**Comment by OneAndOnly1111** [comment]
![image](https://user-images.githubusercontent.com/18378998/81784114-fafadc00-952e-11ea-9cef-426246d327be.png)
![image](https://user-images.githubusercontent.com/18378998/81784172-0cdc7f00-952f-11ea-80b9-9fcc86f87d9c.png)
![image](https://user-images.githubusercontent.com/18378998/81784240-254c9980-952f-11ea-9e1f-cbe29c47037f.png)
使用 mini-ali-ui-rpx Am-switch 开关  在安卓机型上样式正常
在iPhone机型上，仅宽度为375Dpr上显示正常，非375Dpr样式显示有问题，且使用style设置样式无效

**Comment by OneAndOnly1111** [comment]
![ip6](https://user-images.githubusercontent.com/18378998/81784550-9d1ac400-952f-11ea-87c4-ce00c10242bd.jpg)

**Comment by linxz** [comment]
感谢反馈，我们排查一下看看具体导致这个情况的原因。

**Comment by linxz** [comment]
已在 1.0.10 版本中修复。
