### ISSUE TITLE
collapse组件报错

### ISSUE THREAD

**Issue by cyrusli** [Alibaba-mp/mini-ali-ui#24]
![image](https://user-images.githubusercontent.com/4346862/82626643-e7303380-9c1a-11ea-998b-55e6711fab57.png)
版本：1.0.9
`this.$page[collapsePrefix("updates-" + collapseKey)]` 没有初始化

**Comment by linxz** [comment]
请检查一下 `collapse-item` 是否存在，可以参考阅读一下该组件的使用说明文档。

https://github.com/Alibaba-mp/mini-ali-ui/blob/master/src/collapse/index.md

**Comment by cyrusli** [comment]
![image](https://user-images.githubusercontent.com/4346862/82647029-2163fa00-9c48-11ea-8b3e-31933e0e80ac.png)

有collapse-item的。

**Comment by linxz** [comment]
我看到你是把 `collapse` 修改为了 `am-collapse`，那么就是不知道你是否也将 `collapse-item` 也修改了，还请再看一下哦。我根据你截图的代码，尽可能模拟参考，并未看到任何报错。

所以，还请看一下该页面同目录下的 json 文件是否有问题。

```json
{
  "defaultTitle": "Collapse",
  "usingComponents": {
    "collapse": "mini-ali-ui/es/collapse/index",
    "collapse-item": "mini-ali-ui/es/collapse/collapse-item/index"
  }
}
```

**Comment by cyrusli** [comment]
![image](https://user-images.githubusercontent.com/4346862/82651195-69861b00-9c4e-11ea-9d2e-c53d4902f5b9.png)
![image](https://user-images.githubusercontent.com/4346862/82651236-7a369100-9c4e-11ea-9cf6-26c1ee6da25a.png)
![image](https://user-images.githubusercontent.com/4346862/82651379-aa7e2f80-9c4e-11ea-99c9-4d34f6622999.png)

原来usingComponents里面也是命名为am-collapse的，现在改成了collapse依然报错。

**Comment by linxz** [comment]
如果可以的话，提供一份可以复现问题的 demo 吧，目前这样来看，我也想象不到问题所在。

**Comment by cyrusli** [comment]
重现了，groups初始化时是一个空数组就会出现，因为没有collapse-item，所以this.$page[collapsePrefix("updates-" + collapseKey)]并没有被赋值。

**Comment by linxz** [comment]
```xml
<collapse-item
   a:for="{{groups}}"
...
```

按照你的代码来理解，如果 groups 初始为空数组的话，那么也就相当于是 `collapse-item` 是不存在的，所以也就回到前面我所设想的：

> 请检查一下 `collapse-item` 是否存在，可以参考阅读一下该组件的使用说明文档。
> 
> https://github.com/Alibaba-mp/mini-ali-ui/blob/master/src/collapse/index.md

一个折叠面板中内容为空的话，应该就不用显示出来的，不知道要不要考虑一下判断 groups 是否为空，如果为空就不显示整个 `collapse` 组件呢？

**Comment by cyrusli** [comment]
明白了，非常感谢！主要是没留意到collapse-item是必须的，空数组是因为数据还未加载。我先加判断吧。
