### ISSUE TITLE
collapse和amchecbox 初始值不生效

### ISSUE THREAD

**Issue by Aleczhang1992** [Alibaba-mp/mini-ali-ui#25]
version:1.0.10
collapse 设置activeKey无效，指定key面板无法展开；
有如图error
![图片](https://user-images.githubusercontent.com/15828753/83106692-7c399d80-a0ef-11ea-9b72-dd54caf93cc4.png)

amchecbox设定checked=true无效，渲染没有选中状态。使用1.0.5版本正常。

使用环境：remax2.1.1

**Comment by linxz** [comment]
关于 **collapse** 组件的问题，可以参考一下这个 https://github.com/Alibaba-mp/mini-ali-ui/issues/24 或许能解决你的问题。

**am-checkbox** 请参考阅读文档中的属性描述：https://opendocs.alipay.com/mini/component-ext/am-checkbox#%E5%B1%9E%E6%80%A7

**Comment by Aleczhang1992** [comment]
@linxz #24 描述的初始数据为空的判断我加过了，默认展开的情况，arrow-icon状态显示active，但是content内容没有展开

**Comment by linxz** [comment]
@Aleczhang1992 没有展开，但是 arrow 表现又是正常的话，那我现在能猜测的就是你的 `collapse-item` 是空的内容。

```xml
<collapse-item header="标题1" itemKey="item-11" collapseKey="collapse1">
      
    </collapse-item>
```

这些都是只是猜测，如果可以的话，要不提供一个 demo，然后我们排查一下？[点击打开 webIDE 创建 demo](https://hpmweb.alipay.com/bugme/assets/webide?demoId=17000007&subType=DOI00001353&chinfo=minialiui-issue-template)

**Comment by Aleczhang1992** [comment]
@linxz 用demo验证过了，我使用的是钉钉环境，这里没法正常展开默认项，支付宝小程序时正常的，这个是不是不大好解决了~

**Comment by linxz** [comment]
@Aleczhang1992 还请告知一下具体的钉钉小程序的一些信息，比如是钉钉个人应用还是企业应用，如果有钉钉小程序的 sdk 版本信息最佳。

既然现在知道是在钉钉小程序中了，那我这边也就针对性去看一下。感谢。

**Comment by Aleczhang1992** [comment]
dd/SDKVersion: 1.7.95
