### ISSUE TITLE
stepper,值的显示不受手动的setData控制，回调会直接显示

### ISSUE THREAD

**Issue by FairyUmaru** [Alibaba-mp/mini-ali-ui#26]
我们希望如果stepper的value大于某个值时，弹出提示。

现在的效果是：
比如在onChange中设置value大于5提示超出数量。当提示出现时，stepper的显示已经变成6了。
如果设置组件max为5，onChange中这个>5提示超出数量则不会触发。
如果onChange改为中>=5,刚增加到5就会提示。

这个组件值的展示的和onChange回调没有先后关系,导致在有业务判断的时候很难受

**Comment by linxz** [comment]
@FairyUmaru 虽然能够大概明白你的意思，但为了能够更准确的了解到你所描述的问题，建议提供一个可复现的 demo。通过[点击这个链接，在 webIDE 新建一个 demo](https://hpmweb.alipay.com/bugme/assets/webide?demoId=17000007&subType=DOI00001353&chinfo=minialiui-issue-template) 后分享 url 即可。

**Comment by FairyUmaru** [comment]
> @FairyUmaru 虽然能够大概明白你的意思，但为了能够更准确的了解到你所描述的问题，建议提供一个可复现的 demo。通过[点击这个链接，在 webIDE 新建一个 demo](https://hpmweb.alipay.com/bugme/assets/webide?demoId=17000007&subType=DOI00001353&chinfo=minialiui-issue-template) 后分享 url 即可。

https://pen.mini-code.com/s/47f65adb-3b9c-4c62-a5a6-131aa3c5be35

**Comment by linxz** [comment]
> > @FairyUmaru 虽然能够大概明白你的意思，但为了能够更准确的了解到你所描述的问题，建议提供一个可复现的 demo。通过[点击这个链接，在 webIDE 新建一个 demo](https://hpmweb.alipay.com/bugme/assets/webide?demoId=17000007&subType=DOI00001353&chinfo=minialiui-issue-template) 后分享 url 即可。
> 
> https://pen.mini-code.com/s/47f65adb-3b9c-4c62-a5a6-131aa3c5be35

在你的 demo 中，`stepper` 的最大值如果是 3 时（`max="{{3}}"`），后面再点击肯定是无法显示为 4 甚至是更大的值。按照你的需求描述，是希望 `stepper` 的值在已经超过最大值时，用户再次点击 + 就弹出提示，告知用户已经超过加购数量了。而按照组件的设计，`max` 作为最大值是无法超过的。

目前你的 demo 中，`callback` 中判断的是 `value > 3`，由于 `max="{{3}}` 的关系，是无法进入这个判断，不过你可以改为 `value >= 3` 作为判断的依据，提示文案可考虑将“超过”修改为“达到”。

```xml
<stepper step="{{1}}" showNumber="{{true}}" readOnly="{{true}}" value="{{quantity1}}" min="{{1}}" max="{{3}}" onChange="callback"></stepper>
```

```javascript
callback(value) {
  if(value >= 3) {
    my.alert({
      title: '您已达到加购数量'
    })
  }
}
```

![image](https://user-images.githubusercontent.com/1132815/84236188-d55ef380-ab29-11ea-9cc1-4c2d1ffca272.png)

**Comment by FairyUmaru** [comment]
> > > @FairyUmaru 虽然能够大概明白你的意思，但为了能够更准确的了解到你所描述的问题，建议提供一个可复现的 demo。通过[点击这个链接，在 webIDE 新建一个 demo](https://hpmweb.alipay.com/bugme/assets/webide?demoId=17000007&subType=DOI00001353&chinfo=minialiui-issue-template) 后分享 url 即可。
> > 
> > 
> > https://pen.mini-code.com/s/47f65adb-3b9c-4c62-a5a6-131aa3c5be35
> 
> 在你的 demo 中，`stepper` 的最大值如果是 3 时（`max="{{3}}"`），后面再点击肯定是无法显示为 4 甚至是更大的值。按照你的需求描述，是希望 `stepper` 的值在已经超过最大值时，用户再次点击 + 就弹出提示，告知用户已经超过加购数量了。而按照组件的设计，`max` 作为最大值是无法超过的。
> 
> 目前你的 demo 中，`callback` 中判断的是 `value > 3`，由于 `max="{{3}}` 的关系，是无法进入这个判断，不过你可以改为 `value >= 3` 作为判断的依据，提示文案可考虑将“超过”修改为“达到”。
> 
> ```
> <stepper step="{{1}}" showNumber="{{true}}" readOnly="{{true}}" value="{{quantity1}}" min="{{1}}" max="{{3}}" onChange="callback"></stepper>
> ```
> 
> ```js
> callback(value) {
>   if(value >= 3) {
>     my.alert({
>       title: '您已达到加购数量'
>     })
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/1132815/84236188-d55ef380-ab29-11ea-9cc1-4c2d1ffca272.png)

您好，demo中限制max只是其中的一种情况，第二个例子中我也有给出不设置max的情况。因为我们现在正在做的是淘宝小程序，在加购商品时，希望能够和淘宝里的加购表现一致。当等于3时，仍然可以点击给出提醒，但是value不会变为4。您目前给出的更换文案，算是一种解决方式。但是从功能上来说，希望可以考虑下。

**Comment by linxz** [comment]
@FairyUmaru 嗯，好的，你的这个意见我们这边会多加考虑一下。目前还是建议你从交互方式上做处理了，给你带来的不便，十分抱歉。
