### ISSUE TITLE
 纵向Tabs官方示例在钉钉小程序中选中tab的效果不会自动切换，控制台无报错

### ISSUE THREAD

**Issue by zhoutao1** [Alibaba-mp/mini-ali-ui#29]
## 复现步骤

1. 
2. 

### demo 示例

🔗 demo 的示例地址：

## 预期行为
1.
2.

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**
* **设备机型：**
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
@zhoutao1 
虽然在你的标题中描述了使用官方示例，但并不知道你在钉钉中环境。目前通过你的描述仅只能知道代码可能是官方示例。为了能够更好地排查解决问题，还请尽可能详细描述一下，以便于我们能够快速定位问题。

谢谢。

**Comment by zhoutao1** [comment]
页面代码
![图片](https://user-images.githubusercontent.com/25092042/84470828-ba6dba00-acb6-11ea-8ee6-3c799972b06b.png)
js文件
![图片](https://user-images.githubusercontent.com/25092042/84470883-d5402e80-acb6-11ea-9585-b5f175358e83.png)
引入配置
![图片](https://user-images.githubusercontent.com/25092042/84470960-f99c0b00-acb6-11ea-8969-ea6e844016a3.png)
效果如下：
![图片](https://user-images.githubusercontent.com/25092042/84471007-0fa9cb80-acb7-11ea-9b35-ee4857eb4637.png)
点击第个tab效果如下：
![图片](https://user-images.githubusercontent.com/25092042/84471090-39fb8900-acb7-11ea-9d15-9b088dddf4f0.png)
没有自动切换tab的选中！

**Comment by dasoncheng** [comment]
你的事件参数提取有问题，实际是({ index:number, tabsName:string })=>void，而文档里是(index:number)=>void

**Comment by linxz** [comment]
请确认使用的钉钉小程序 SDK 版本是否为最新版本。
如使用低版本的 SDK，在钉钉小程序中会有兼容问题。

https://ding-doc.dingtalk.com/doc#/dev/hi3eyb
