### ISSUE TITLE
验证码框可重复点击

### ISSUE THREAD

**Issue by init-qy** [Alibaba-mp/mini-ali-ui#30]
## 问题描述

1.验证码框组件（verify-code）组件可重复点击，具体表现为源码不校验 _actionActive状态，setInterval多次
2.如果手机号输入错误，无法发送验证码时，该组件一定会进入倒计时，希望由组件调用方控制状态

## 复现步骤

1. 不断点击发送验证码那个窗口即可

### demo 示例

🔗 demo 的示例地址：
https://pen.mini-code.com/s/75005a16-911d-4c87-8e25-2dce70ba4cc1

## 预期行为
1.
2.

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**1.0.11
* **设备机型：**
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
可重复点击的这个问题，下个版本会处理。
这周就会发布新的一个版本。

**Comment by linxz** [comment]
@init-qy 已经在 1.0.12 版本中修复。

**Comment by init-qy** [comment]
@linxz 感谢修复
