### ISSUE TITLE
验证码发送组件，必须先填写验证码才能触发发送？

### ISSUE THREAD

**Issue by yxlm1994** [Alibaba-mp/mini-ali-ui#31]
## 问题描述
mini-ali-ui  1.0.12版本
新特性 verify-code 组件未输入值情况下的验证提示；导致
点击获取验证码按钮时，必须先输入验证码，这个时候根本就还没有验证码

## 复现步骤

1. 验证码功能输入手机号，然后点击发送验证码就提示要先填验证码了

**Comment by linxz** [comment]
@yxlm1994 看来是我这边对这个使用场景的理解有误，我这边捋一下。感谢反馈。

**Comment by linxz** [comment]
@yxlm1994 不知道你期望是效果是图中的情况。

![image](https://user-images.githubusercontent.com/1132815/85003467-d4ad0980-b188-11ea-9014-8ac8c5889a3e.png)

```xml
<verify-code data-field="verifyCode" 
    onInput="onInput" 
    value="{{verifyCode}}" 
    placeholder="请输入手机号"
    label="手机号"
    verifyTip="手机号不能为空"
    onClear="onClear" 
    last="{{true}}" 
    countDown="{{10}}" 
    onSend="onSend"></verify-code>
```

然而现在看到的是结果是“验证码不能为空”

![image](https://user-images.githubusercontent.com/1132815/85003674-18a00e80-b189-11ea-8fe1-ed90f4e2ebb1.png)

从这里来看，似乎应该是默认的文案导致的关系。
如果是因为文案的关系，那么可以考虑加上这三个属性来处理：

```
 placeholder="请输入手机号"
label="手机号"
verifyTip="手机号不能为空"
```

**Comment by yxlm1994** [comment]
手机号已经填了，但是发现发送验证码，必须要在验证码框内填上字符才能触发；这很奇怪，我就是为了触发发送验证码，但是却要求先填写验证码，大致是这么个情况；在验证码框内填上任意字符后就可以触发获取验证码方法了

**Comment by linxz** [comment]
@yxlm1994 感谢，跟相关人员沟通之后，这块的确是多余的一个操作，已经在 1.0.13 版本中去掉。
