### ISSUE TITLE
collapse 手风琴模式 activeKey 设置无效，始终展开第一项/最后一项。

### ISSUE THREAD

**Issue by yinzhuoya** [Alibaba-mp/mini-ali-ui#35]
## 复现步骤

1. accordion="{{true}}" activeKey="{{[1]}}" 设置activeKey无效 默认展开第一项/最后一项

### demo 示例

🔗 demo 的示例地址：https://pen.mini-code.com/s/deebdfb3-1dce-4ad3-a377-c5efe798145e

## 预期行为
1.按照activeKey设置展开

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**
* **设备机型：**
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
@yinzhuoya 根据你的描述，未复现。并且你提供的 demo 并不是分享形式的 url，无法查看哦。

**Comment by yinzhuoya** [comment]
> @yinzhuoya 根据你的描述，未复现。并且你提供的 demo 并不是分享形式的 url，无法查看哦。

demo 链接已更新 麻烦在帮忙看一下吧
![image](https://user-images.githubusercontent.com/16454398/87035090-6c979380-c21b-11ea-89be-9e59ae97b01f.png)

**Comment by linxz** [comment]
@yinzhuoya 手风琴模式因为打开的只会有一个，传字符串类型的值给 `activeKey` 就可以了。默认手风琴打开的都是第一个，如果取值错误的话，那就是第一个了……

然后你的代码中使用的是 `{{index}}`，我想或许你需要考虑换成了 `{{item}}` 比较合适。
