### ISSUE TITLE
在popup组件中遇到radio改变后，popup关闭并再次打开popup后，radia选中项无法渲染的问题

### ISSUE THREAD

**Issue by luobinziyue** [Alibaba-mp/mini-ali-ui#37]
## 复现步骤

1. 
2. 

### demo 示例

🔗 demo 的示例地址：

## 预期行为
1.
2.

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**
* **设备机型：**
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
请详细描述一下具体使用的版本、环境，便于排查问题。
