### ISSUE TITLE
Tabs的Plus Icon是否支持自定义

### ISSUE THREAD

**Issue by nekronhuang** [Alibaba-mp/mini-ali-ui#40]
## 背景
> 请描述你所遇到的问题现状

业务需求其实是因为tab项太多，希望增加一个icon可以触发快速选中的操作。但由于Tabs组件该位置写死了`<am-icon type="add" />`。

## 期望
> 请描述你所希望添加的功能

期望开放此处的icon自定义能力。

## 思路
> 对于你所描述的问题，是否已有解决方案或者思路，如有可提供作为参考，或者提交你的 PR 、截图

如果期望收敛需求，可以增加iconType；不然，期望增加完全自定义的槽位。

**Comment by linxz** [comment]
这个需求情况我们这边也有所思考，具体的后续会找相关人员沟通。感谢
