### ISSUE TITLE
button loading 状态还能点击？

### ISSUE THREAD

**Issue by closertb** [Alibaba-mp/mini-ali-ui#41]
## 问题描述
在任何前端状态交互中，给button 加了loading状态，为什么loading态组件还能接着点击，这似乎不太符合常规逻辑？

## 复现步骤

1. 
2. 

### demo 示例

🔗 demo 的示例地址：https://opendocs.alipay.com/mini/component/button

### 截图

![image](https://user-images.githubusercontent.com/22979584/88528096-c2987380-d030-11ea-90a8-d21fbcc5fc6c.png)

## 预期行为
1. 点了button loading态后应该不能接着点

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**
* **设备机型：**
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
有 loading 并不一定是不可点击，如果想要不可点击的话，可以考虑加载禁用的属性。
不知道这样的处理方式是否能够满足你的需求呢？

**Comment by closertb** [comment]
> 有 loading 并不一定是不可点击，如果想要不可点击的话，可以考虑加载禁用的属性。
> 不知道这样的处理方式是否能够满足你的需求呢？

目前确实是这样处理的。但从antd 与 antd-mobile 的交互上，都将loading 默认禁用，小程序以前没写过，不知道这样的设计的出发点在什么场景呢？

**Comment by linxz** [comment]
> > 有 loading 并不一定是不可点击，如果想要不可点击的话，可以考虑加载禁用的属性。
> > 不知道这样的处理方式是否能够满足你的需求呢？
> 
> 目前确实是这样处理的。但从antd 与 antd-mobile 的交互上，都将loading 默认禁用，小程序以前没写过，不知道这样的设计的出发点在什么场景呢？

理论上，loading 是加载的过程，不建议用户再有更多的操作，不过在 button 中已有 `disabled` 属性作为依托，在考虑可能会有场景在 loading 的过程做其他操作，因此这里并未对 loading 状态做禁用处理，而是把这个主动权交给开发者自行决定。

```xml
<button type="primary" loading disabled>Loading</button>
```
![image](https://user-images.githubusercontent.com/1132815/91796220-37735480-ec52-11ea-9c54-3d14af73736c.png)

如上即可在 loading 状态下禁用 button。
