### ISSUE TITLE
是否有计划支持 typescript

### ISSUE THREAD

**Issue by k55k32** [Alibaba-mp/mini-ali-ui#42]
## 背景
> 请描述你所遇到的问题现状

## 期望
> 请描述你所希望添加的功能

## 思路
> 对于你所描述的问题，是否已有解决方案或者思路，如有可提供作为参考，或者提交你的 PR 、截图

**Comment by linxz** [comment]
mini-ali-ui 作为小程序的扩展组件，是期望能够直接通过 npm 方式引入使用，主要是以小程序的自定义形式介入，并未考虑额外开发使用。

![image](https://user-images.githubusercontent.com/1132815/91795801-3261d580-ec51-11ea-8093-818f60e34de8.png)
https://opendocs.alipay.com/mini/framework/custom-component-overview

参照自定义组件的介绍，并未考虑支持 typescript。

**Comment by aizigao** [comment]
我看源码是ts，不能直接生成.d.ts文件吗

**Comment by laogui** [comment]
缺声明文件，目前在remaxjs里用了这个UI库，用的挺好，就是引用方式不太美观 `import AmIcon from 'mini-ali-ui/es/am-icon'`
