### ISSUE TITLE
notice滚动不生效

### ISSUE THREAD

**Issue by imgss** [Alibaba-mp/mini-ali-ui#47]
## 问题描述

在淘宝pc端小程序，引入`<notice>`组件，设置`enableMarquee="{{true}}" marqueeProps="{{marqueeProps}}"`，字符长度足够，但是滚动没有生效

## 复现步骤

1. 在pc页面的某个组件中引入notice
2. 后续步骤如描述

3.排查下来是      [my.createSelectorQuery().exec()](https://github.com/Alibaba-mp/mini-ali-ui/blob/75aa5b30b2f90b70aefc2cd55d2741a5f57ff63e/src/notice/index.ts#L116)的回调函数没有被调用

在setTimeout(()=>{...},0)里面调用createSelectorQuery，正常滚动。如果官方认可这个原因的话，我可以提一个PR

### demo 示例

🔗 demo 的示例地址：

### 截图

![image](https://user-images.githubusercontent.com/20496797/96699626-1103a700-13c1-11eb-91c4-6817145659ce.png)

## 预期行为
1. notice可以滚动
2.
![image](https://user-images.githubusercontent.com/20496797/96699532-f3364200-13c0-11eb-9883-e648ffb9c6ad.png)

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**
* **设备机型：**
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
感谢你的 pr，我会尽快验证一下。
