### ISSUE TITLE
remax中使用 mini-ali-ui在小程序ide中构建失败

### ISSUE THREAD

**Issue by SeaStars-beep** [Alibaba-mp/mini-ali-ui#49]
## 复现步骤

1. 
2. 

### demo 示例

🔗 demo 的示例地址：

### 截图

![image](https://user-images.githubusercontent.com/72014072/96810308-1f4bd480-144e-11eb-9571-c5ef01560662.png)
![image](https://user-images.githubusercontent.com/72014072/96810579-338fd180-144e-11eb-818a-547587f691b8.png)

## 预期行为
1.
2.

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：** 1.1.7
* **设备机型：** 小程序ide
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
沟通结果：在 IDE 中开启了 remax 和外部手动开启 remax，两者冲突导致。
