### ISSUE TITLE
am-icon 在钉钉小程序中 color属性不生效

### ISSUE THREAD

**Issue by init-qy** [Alibaba-mp/mini-ali-ui#50]
## 问题描述

am-icon 在钉钉小程序中 color属性不生效，在支付宝小程序中表现正常
现在一个临时的解决方案是通过className对color进行赋值
.axml
`<am-icon type="more-1" color="#3699FE" size="32" className="item-name"/>`
.acss
`.item-name {
    color: #3699FE;
}`
## 复现步骤

1. 
2. 

### demo 示例

🔗 demo 的示例地址：

## 预期行为
1.
2.

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [x] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**1.1.7
* **设备机型：**
* **设备版本：**
* **APP：** 钉钉小程序

**Comment by linxz** [comment]
![image](https://user-images.githubusercontent.com/1132815/97003992-ece5c880-156e-11eb-891e-3b68f926b579.png)

在钉钉小程序中是可以看到颜色的变化的。因为这里使用的是 CSS 自定义属性，或许可能是兼容性的问题导致无法识别。

`{{color?'--am-icon-color:' + color + ';':''}}"`

不过用 `className`  的方式也是一个方案……

**Comment by init-qy** [comment]
好吧，更新了ide后显示正常了...
