### ISSUE TITLE
input-item 组件希望能增加设置清除按钮大小的功能

### ISSUE THREAD

**Issue by init-qy** [Alibaba-mp/mini-ali-ui#51]
## 背景
> 在input-item 组件中，清除按钮大小是无法自定义设置，在px版本中18的大小正常，但是在rpx版本中18的大小显得过小
`      <am-icon size="18" 
        class="am-input-clear-icon" 
        type="close_" 
        color="#ccc" />`
附图rpx版本
![image](https://user-images.githubusercontent.com/59350883/97130721-20963d80-177d-11eb-9b86-ee818f1cb17b.png)
附图px版本
![image](https://user-images.githubusercontent.com/59350883/97130851-8a164c00-177d-11eb-993c-fcc4048898f9.png)
在真机测试上表现与ide相同

## 期望
>input-item 组件希望能增加设置清除按钮大小的功能

## 思路
> 可以对rpx版本进行优化，修改默认的清除按钮大小；或者开放自定义清除按钮大小，更开放一点可以修改清除按钮图标或者开放插槽

**Comment by linxz** [comment]
在 **rpx** 版本中的确是有这个情况，我们尽快处理，使其保持跟 **px** 版本的效果一致。
目前你暂时可是通过修改这个 `input-item` 组件的 CSS 方式来覆盖。
```css
.am-input-clear-icon {
  /* 根据你的需求修改 font-size 即可 */
  font-size: 44rpx;
}
```

**Comment by linxz** [comment]
在 rpx 版本中 icon 显得比较小的问题，已经在 1.2.0 版本中修复了。
