### ISSUE TITLE
SwipeAction功能问题

### ISSUE THREAD

**Issue by xichangzhou** [Alibaba-mp/mini-ali-ui#57]
SwipeAction可滑动单元格每次点击单元格onSwipeStart这个方法会执行，能不能使这个方法只有在单元格滑动的时候才执行？获取有没有一个单元格滑动开执行的方法，不然没办法在单击单元格的时候，使已经滑开的单元格关闭，还不执行单击的单元格的方法？

**Comment by linxz** [comment]
> 不然没办法在单击单元格的时候，使已经滑开的单元格关闭，还不执行单击的单元格的方法？

所以，你的诉求是希望滑开的单元格在点击的将关闭和执行单元格的方法分开，是吗？

**Comment by linxz** [comment]
长时间未有后续，暂时先关闭，如有需要可再打开沟通。
