### ISSUE TITLE
有没有做上传组件的计划呢？

### ISSUE THREAD

**Issue by arieslee** [Alibaba-mp/mini-ali-ui#58]
## 背景
> 想在钉钉小程序中上传视频文件，需要分片上传的功能

## 期望
> 希望添加上传组件

## 思路
> 无

**Comment by linxz** [comment]
十分抱歉，目前为止暂无开发上传组件的计划。
如有需求可通过 [my.uploadFile](https://opendocs.alipay.com/mini/api/kmq4hc) 自行实现上传的需求。
