### ISSUE TITLE
ctrlchecked的初始默认值问题

### ISSUE THREAD

**Issue by mfoonirlee** [Alibaba-mp/mini-ali-ui#59]
## 问题描述

在受控模式下，仅设置ctrlChecked为true时，无法正确的显示组件的勾选状态

## 复现步骤

1. 目前的 onInit 与didMount仅会从props中去获得checkbox的默认值，且读取的值为checked，不会读取受控状态下的ctrlChecked的值
2. 只要组件没有触发deriveDataFromProps钩子，在受控状态下则组件状态会无法被正确设置

### demo 示例

🔗 demo 的示例地址：

## 预期行为
1.
2.

## 环境信息

* [x] mini-ali-ui （px 版本扩展组件）
* [ ] mini-ali-ui-rpx （rpx 版本扩展组件）

* **组件库版本：**
* **设备机型：**
* **设备版本：**
* **APP：** 支付宝小程序

**Comment by linxz** [comment]
如要使用受控模式，需要开启 **component2编译**

**Comment by mfoonirlee** [comment]
现在的问题就是component2编译之后的包，运行出现的，效果为
<am-checkbox
      ctrlChecked="{{ctrlChecked}}"
      disabled="{{disabled}}"
    />
当ctrlChecked为false，disabled为true，显示的效果为禁用且未勾选，原因如issue中分析所示

**Comment by linxz** [comment]
![image](https://user-images.githubusercontent.com/1132815/101483240-d5ce2f00-3992-11eb-94bc-0576781f2210.png)
![image](https://user-images.githubusercontent.com/1132815/101483264-dff02d80-3992-11eb-89d8-fef7cc9065a0.png)
![temp](https://user-images.githubusercontent.com/1132815/101483673-7ae90780-3993-11eb-8102-bb2dc21d7732.gif)

按照你的描述，这个是正常的情况。
> 当ctrlChecked为false，disabled为true，显示的效果为禁用且未勾选

而在前面你的分析中，在 gif 图中可以看到，变化展示是没有问题的。
如果可以的话，还请提供一个 demo，我们来验证一下。

**Comment by mfoonirlee** [comment]
是打包后的产物的问题
