### ISSUE TITLE
多行文本，ios下文本给顶出文本框

### ISSUE THREAD

**Issue by myGitZone** [Alibaba-mp/mini-ali-ui#60]
最新版本的组件库。
![啊啊啊](https://user-images.githubusercontent.com/19903630/101900916-38ba0300-3beb-11eb-9b70-9ee625b6b743.png)

碰到问题是ios最新系统，文本给顶出了输入框。
demo代码
[blank1.zip](https://github.com/Alibaba-mp/mini-ali-ui/files/5678979/blank1.zip)

**Comment by myGitZone** [comment]
不清楚为什么从原来的默认false -> undefined

**Comment by linxz** [comment]
我这边试了一下你的 demo 并没有发现这个问题。
对于表单输入的相关问题，可以通过 https://opensupport.alipay.com/support/helpcenter/144/201602630402#anchor__3 这里查询

不知道你现在所遇到的问题是什么？能否具体的描述一下呢？

**Comment by myGitZone** [comment]
[blank1.zip](https://github.com/Alibaba-mp/mini-ali-ui/files/5679462/blank1.zip)
不好意思，demo中的ui版本锁了，这个是可以重现的

**Comment by myGitZone** [comment]
![share](https://user-images.githubusercontent.com/19903630/101911511-69099d80-3bfb-11eb-85db-a601d3915db7.jpg)
这个样子的，现在需要加上 enableNative={{false}}，不知道这里为什么把默认的false -> undefined。

**Comment by linxz** [comment]
改为 undefined 主要是为了将表单输入部分的属性值保持统一，当时验证的时候的没发现你说的这个情况，实在抱歉。
现在这个情况只有请加上 `enableNative="{{false}}"` 来处理。

由于验证不到位给你到来的困扰，再次表示道歉，后续对于这类验证一定更严格把关。
