### ISSUE TITLE
search-bar onSubmit 事件触发后不失焦,且无法通过focus prop来让search-bar失焦

### ISSUE THREAD

**Issue by lixin0724** [Alibaba-mp/mini-ali-ui#62]
## 背景
> 请描述你所遇到的问题现状

1.search-bar 组件 onSubmit 事件触发后不失焦。
2.无法通过focus prop来让search-bar失焦。

## 期望
> 请描述你所希望添加的功能

1. search-bar组件 onSubmit触发后自动失焦
2. focus支持通过prop实时更新。

## 思路
> 对于你所描述的问题，是否已有解决方案或者思路，如有可提供作为参考，或者提交你的 PR 、截图
![image](https://user-images.githubusercontent.com/53106140/103405111-f6079d00-4b90-11eb-8eb4-3e518e4a681c.png)
![image](https://user-images.githubusercontent.com/53106140/103405152-1899b600-4b91-11eb-8afa-9478f573afa2.png)

**Comment by linxz** [comment]
感谢反馈

**Comment by linxz** [comment]
> 1. search-bar组件 onSubmit触发后自动失焦
当 onSubmit 之后，键盘已经收起，且输入框后面的清除 icon 也消失。也可以通过 `onBlur` 进行测试，当输入完毕，回车后，可以看到是已触发了。

![image](https://user-images.githubusercontent.com/1132815/104012767-58911680-51eb-11eb-846e-99878c452804.png)
![image](https://user-images.githubusercontent.com/1132815/104012792-60e95180-51eb-11eb-855c-1cb494a1c198.png)
![image](https://user-images.githubusercontent.com/1132815/104012809-69da2300-51eb-11eb-99b8-604310a33357.png)
![image](https://user-images.githubusercontent.com/1132815/104012854-7fe7e380-51eb-11eb-809b-ef22ae42783b.png)

> 2. focus支持通过prop实时更新。

`focus` 本身是支持的，但是基于 iOS 的某些特性要求，有所收敛。
