### ISSUE TITLE
SearchBar 搜索框confirm-type="search"不生效

### ISSUE THREAD

**Issue by applerao** [Alibaba-mp/mini-ali-ui#65]
## 背景
> 请描述你所遇到的问题现状

SearchBar 搜索框confirm-type="search"不生效，变成了驼峰confirmType="search"
## 期望
> 请描述你所希望添加的功能

部分由短横线-拼接的保留字如confirm-type不要按照dataset改成驼峰

## 思路
> 对于你所描述的问题，是否已有解决方案或者思路，如有可提供作为参考，或者提交你的 PR 、截图

**Comment by linxz** [comment]
https://github.com/Alibaba-mp/mini-ali-ui/blob/4098aa899ce581ed84c19c1dff9e1e5a31e78f07/src/search-bar/index.axml#L9
在这里可以看到 search-bar 中使用了 `input` 的 `confirm-type="search"`，并未看到你所说的驼峰 `confirmType="search"`。

如果是在真机上未看到键盘中出现 ”搜索“ 字样，可以考虑尝试给 **search-bar** 添加一个 `enableNative="{{true}}"` 属性（值）。

**Comment by applerao** [comment]
> https://github.com/Alibaba-mp/mini-ali-ui/blob/4098aa899ce581ed84c19c1dff9e1e5a31e78f07/src/search-bar/index.axml#L9
> 
> 
> 在这里可以看到 search-bar 中使用了 `input` 的 `confirm-type="search"`，并未看到你所说的驼峰 `confirmType="search"`。
> 如果是在真机上未看到键盘中出现 ”搜索“ 字样，可以考虑尝试给 **search-bar** 添加一个 `enableNative="{{true}}"` 属性（值）。

search-bar里是confirm-type，但是调试时可以看到端横线-确实都处理成了驼峰，见图。
<img width="465" alt="截屏2021-02-20 上午10 30 56" src="https://user-images.githubusercontent.com/1898210/108580522-c7bf6600-7366-11eb-9ebd-4bf10fdfadcd.png">

不过，enableNative确实解决了这个问题，文档上说enableNative可以解决输入框闪动的问题，倒是没有提到这个点。

**Comment by linxz** [comment]
> > https://github.com/Alibaba-mp/mini-ali-ui/blob/4098aa899ce581ed84c19c1dff9e1e5a31e78f07/src/search-bar/index.axml#L9
> > 
> > 在这里可以看到 search-bar 中使用了 `input` 的 `confirm-type="search"`，并未看到你所说的驼峰 `confirmType="search"`。
> > 如果是在真机上未看到键盘中出现 ”搜索“ 字样，可以考虑尝试给 **search-bar** 添加一个 `enableNative="{{true}}"` 属性（值）。
> 
> search-bar里是confirm-type，但是调试时可以看到端横线-确实都处理成了驼峰，见图。
> <img alt="截屏2021-02-20 上午10 30 56" width="465" src="https://user-images.githubusercontent.com/1898210/108580522-c7bf6600-7366-11eb-9ebd-4bf10fdfadcd.png">
> 
> 不过，enableNative确实解决了这个问题，文档上说enableNative可以解决输入框闪动的问题，倒是没有提到这个点。

你说的这个驼峰问题，我猜想可能是底层处理的问题，这个跟 mini-ali-ui 这个组件库并无太大关联。
`input` 的问题有时候挺奇怪的，这里有一个网址，你可以参考一下：https://opensupport.alipay.com/support/helpcenter/144/201602630402

**Comment by applerao** [comment]
> > > https://github.com/Alibaba-mp/mini-ali-ui/blob/4098aa899ce581ed84c19c1dff9e1e5a31e78f07/src/search-bar/index.axml#L9
> > > 
> > > 在这里可以看到 search-bar 中使用了 `input` 的 `confirm-type="search"`，并未看到你所说的驼峰 `confirmType="search"`。
> > > 如果是在真机上未看到键盘中出现 ”搜索“ 字样，可以考虑尝试给 **search-bar** 添加一个 `enableNative="{{true}}"` 属性（值）。
> > 
> > 
> > search-bar里是confirm-type，但是调试时可以看到端横线-确实都处理成了驼峰，见图。
> > <img alt="截屏2021-02-20 上午10 30 56" width="465" src="https://user-images.githubusercontent.com/1898210/108580522-c7bf6600-7366-11eb-9ebd-4bf10fdfadcd.png">
> > 不过，enableNative确实解决了这个问题，文档上说enableNative可以解决输入框闪动的问题，倒是没有提到这个点。
> 
> 你说的这个驼峰问题，我猜想可能是底层处理的问题，这个跟 mini-ali-ui 这个组件库并无太大关联。
> `input` 的问题有时候挺奇怪的，这里有一个网址，你可以参考一下：https://opensupport.alipay.com/support/helpcenter/144/201602630402

你说的是的，和组件库本身没有关系，是小程序做的处理，谢了。
