### ISSUE TITLE
缺少分隔符组件

### ISSUE THREAD

**Issue by taosin** [Alibaba-mp/mini-ali-ui#8]
目前的 UI框架中没有分隔符（Divider）组件，如下图所示：

![-w240px](http://images.iamtaoxin.com/mweb/2020-03-03-15832486045689%20.png)

是否可以添加个呢
😄😄😄

**Comment by linxz** [comment]
这个类似的组件已经在计划中，相信很快就会更新出来了。

**Comment by taosin** [comment]
👍，坐等

**Comment by linxz** [comment]
已经更新，目前在 1.0.4 版本中可在 footer 组件中使用 `type='end'` 来实现
https://github.com/Alibaba-mp/mini-ali-ui/blob/master/src/footer/index.md
