### ISSUE TITLE
collapse has fixed height which should be dynamic

### ISSUE THREAD

**Issue by FelixAnna** [Alibaba-mp/mini-ali-ui#9]
Do you want to request a feature or report a bug?
Report a bug

What is the current behavior?
If we add content (ex: a view in new line) in collapse, it will not shown, because the height is fixed, we can make it dynamic.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code.

<collapse-item header="配置商品选项" itemKey="item-11" collapseKey="collapse1">
          <view line1>
         <view line2>
         .......
</collapse>
 <button click to add new view linex>

What is the expected behavior?
the collapse auto extend in height after we add new item inside it.

Which versions of ``mini-ali-ui``, and which version of ``Alipay`` are affected by this issue? Did this work in previous versions of ``mini-ali-ui``?
1.0.2

**Comment by FelixAnna** [comment]
--- a/src/collapse/collapse-item/index.axml
+++ b/src/collapse/collapse-item/index.axml
@@ -24,7 +24,7 @@
   </view>
   <view
     class="am-collapse-item-content-wrapper"
-    style="max-height: {{contentHeight}}px"
+    style="**{{isActive ? 'max-height: 100%' : 'max-height: 0px'}}**"
   >

**Comment by linxz** [comment]
In the collapse component's demo, `.content1` has a height, so it's fixed.
`max-height` and `height` work differently.
The contents of `<collapse-item></collapse-item>` are customizable by the developer.
We will optimize the demo code to avoid misunderstandings

https://github.com/Alibaba-mp/mini-ali-ui/blob/master/demo/pages/collapse/index.acss#L8
```css
.content1 {
  height: 300rpx;
}
```

https://github.com/Alibaba-mp/mini-ali-ui/blob/master/demo/pages/collapse/index.axml#L10
```xml
<view class="item-content content1">
   <view>内容区域</view>
</view>
```
